### ISSUE TITLE
Add some basic monitoring

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-classification-api#11]
pingdom check'd do :-)

**Comment by lc512k** [comment]
- [ ] https://my.pingdom.com/reports/uptime#check=2038721&tab=uptime_tab&daterange=7days
- [ ] Add to Service Registry

**Comment by matthew-andrews** [comment]
bronze for now is ok :)

**Comment by lc512k** [comment]
https://github.com/Financial-Times/next-service-registry/pull/8
